// src/pages/Dashboard/index.vue
<template>
  <div class="dashboard">
    <el-card class="card-container">
      <template #header>
        <div class="card-header">
          <i class="el-icon-pie-chart"></i>
          <span>总计容量</span>
        </div>
      </template>
      <span v-if="typeof info.usage === 'string'" class="card-desc">{{info.usage}}</span>
      <template v-else>
        <span class="card-desc">{{info.usage[0]}}</span>
        <span class="smallUnit">{{info.usage[1]}}</span>
      </template>
    </el-card>
    <el-card class="card-container">
      <template #header>
        <div class="card-header">
          <i class="el-icon-money"></i>
          <span>总计对象</span>
        </div>
      </template>
      <span class="card-desc">{{info.objects}}</span>
    </el-card>
  </div>
</template>

<script lang="ts">
import {
  defineComponent,
  watchEffect,
  reactive,
  SetupContext
} from 'vue'
import { getDashboardInfo } from '@/api/user'
import { error } from '@/utils/error'
import { niceBytes } from '@/utils/format'

import {
  ElCard
} from 'element-plus'

interface DashBaoardType {
  usage?: string | string[],
  objects?: number | string
}
export default defineComponent({
  name: 'Dashboard',
  components: {
    ElCard
  },
  props: {
    loading: Boolean
  },
  emits: ['update:loading'],
  setup(_, context) {
    const info = reactive<DashBaoardType>({
      usage: '0',
      objects: 0
    })
    const prettyUsage = (usage: string | undefined) => {
      if (usage === undefined) {
        return '0'
      }

      const niceBytesUsage = niceBytes(usage).split(" ");

      if (niceBytesUsage.length !== 2) {
        return niceBytesUsage.join(" ")
      }

      return niceBytesUsage
    }
    const prettyNumber = (usage: number | undefined) => {
      if (usage === undefined) {
        return 0
      }

      return usage.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',')
    }
    watchEffect(() => {
      context.emit('update:loading', true)
      getDashboardInfo()
        .then(res => {
          const { usage, objects } = res.data
          info.usage = prettyUsage(`${usage}`)
          info.objects = prettyNumber(objects)
        })
        .catch(error)
        .finally(() => {
          context.emit('update:loading', false)
        })
    })
    return {
      info
    }
  },
})
</script>

<style lang="scss" scoped>
.dashboard {
  display: flex;
  align-items: center;
}
.card-container {
  margin-left: 20px;
  width: 280px;
  &:first-child {
    margin-left: 0;
  }
}
.card-header {
  color: #777777;
  span {
    margin-left: 8px;
    font-size: 14px;
  }
}
.card-desc {
  color: #000000;
  font-size: 60px;
  font-weight: bold;
}
.smallUnit {
  font-size: 16px;
  font-weight: 500;
  margin-left: 4px;
}
</style>

// src/pages/Dashboard/index.tsx
import { FC } from 'types/index'
import { useEffect, useState } from 'react'
import { getDashboardInfo, DashboardInfoType } from 'api/user'
import { error } from 'lib/error'
import { niceBytes } from 'lib/format'

import { Card } from 'antd'
import Icon from 'components/Icon'
import Loading from 'components/Loading'

import styles from './index.module.scss'

const { Meta } = Card

const bodyStyle = {
  width: '246px',
  minHeight: '165px',
}

function formatUsage(usage: number) {
  if (usage === undefined) {
    return '0'
  }

  const niceBytesUsage = niceBytes(`${usage}`).split(' ')

  if (niceBytesUsage.length !== 2) {
    return niceBytesUsage.join(' ')
  }
  return (
    <>
      {niceBytesUsage[0]}
      <span className={styles.smallUnit}>{niceBytesUsage[1]}</span>
    </>
  )
}

const prettyNumber = (usage: number | undefined) => {
  if (usage === undefined) {
    return 0
  }

  return usage.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',')
}

const Dashboard: FC = () => {
  const [dashboardInfo, setDashboardInfo] = useState<DashboardInfoType>({
    buckets: 0,
    objects: 0,
    usage: 0,
  })
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    setLoading(true)
    getDashboardInfo()
      .then((res) => {
        setDashboardInfo(res.data)
      })
      .catch(error)
      .finally(() => {
        setLoading(false)
      })
  }, [])
  return (
    <div className={styles.container}>
      {
        loading
          ? <Loading />
          : (
            <>
              <Card bodyStyle={bodyStyle} style={{ marginRight: '20px' }}>
                <Meta
                  className={styles['card-desc']}
                  avatar={
                    <Icon type="FieldTime" size="18px" />
                    }
                  title="总计容量"
                  description={formatUsage(dashboardInfo.usage)}
                />
              </Card>
              <Card bodyStyle={bodyStyle}>
                <Meta
                  avatar={
                    <Icon type="Block" size="18px" />
                    }
                  title="总计对象"
                  description={prettyNumber(dashboardInfo.objects)}
                  className={styles['card-desc']}
                />
              </Card>
            </>
          )
      }
    </div>
  )
}

export default Dashboard
